export const CHECK_AUTH_REQUEST = 'CHECK_AUTH_REQUEST'
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS'
export const CHECK_AUTH_FAILURE = 'CHECK_AUTH_FAILURE'

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'